# Generated by Django 2.2.4 on 2019-09-25 03:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnnAgeView',
            fields=[
                ('Age', models.IntegerField(primary_key=True, serialize=False)),
                ('Action', models.IntegerField(default=0)),
                ('Adventure', models.IntegerField(default=0)),
                ('Animation', models.IntegerField(default=0)),
                ('Childrens', models.IntegerField(default=0)),
                ('Comedy', models.IntegerField(default=0)),
                ('Crime', models.IntegerField(default=0)),
                ('Documentary', models.IntegerField(default=0)),
                ('Drama', models.IntegerField(default=0)),
                ('Fantasy', models.IntegerField(default=0)),
                ('FilmNoir', models.IntegerField(default=0)),
                ('Horror', models.IntegerField(default=0)),
                ('Musical', models.IntegerField(default=0)),
                ('Mystery', models.IntegerField(default=0)),
                ('Romance', models.IntegerField(default=0)),
                ('SciFi', models.IntegerField(default=0)),
                ('Thriller', models.IntegerField(default=0)),
                ('War', models.IntegerField(default=0)),
                ('Western', models.IntegerField(default=0)),
                ('Max_genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=500)),
                ('view_cnt', models.IntegerField(default=0)),
                ('tmdb_id', models.IntegerField(default=0)),
                ('poster_path', models.TextField(default='')),
                ('overview', models.TextField(default='')),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('timeStamp', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='M', max_length=10)),
                ('age', models.IntegerField(default=25)),
                ('occupation', models.CharField(max_length=200)),
                ('is_subscribe', models.BooleanField(default=False)),
                ('subscribe_expire', models.DateTimeField(default=datetime.datetime(2019, 9, 25, 12, 33, 46, 389496))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='movieCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
        ),
    ]
