# Generated by Django 2.2.4 on 2019-10-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190930_1605'),
        ('api', '0002_auto_20190926_1431'),
    ]

    operations = [
    ]
