# Generated by Django 2.2.4 on 2019-09-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_moviecluster'),
        ('api', '0002_movie_year'),
    ]

    operations = [
    ]
