# Generated by Django 2.2.4 on 2019-10-08 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20191004_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 9, 27, 52, 604657)),
        ),
    ]
