# Generated by Django 2.2.4 on 2019-09-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20190906_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=None),
        ),
    ]
