# Generated by Django 2.2.4 on 2019-09-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190909_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribe_expire',
        ),
        migrations.AddField(
            model_name='profile',
            name='dd',
            field=models.IntegerField(default=0),
        ),
    ]
