# Generated by Django 2.2.4 on 2019-09-09 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190909_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dd',
        ),
    ]
