# Generated by Django 2.2.4 on 2019-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_profile_dd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=None),
        ),
    ]
