# Generated by Django 2.2.4 on 2019-09-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_subscribe_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default='0000-00-00'),
        ),
    ]
