# Generated by Django 2.2.4 on 2019-09-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190909_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribe_expire',
        ),
    ]
