# Generated by Django 2.2.4 on 2019-09-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_profile_subscribe_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
