# Generated by Django 2.2.4 on 2019-09-09 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190909_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 5, 9, 48, 579353, tzinfo=utc)),
        ),
    ]
