# Generated by Django 2.2.4 on 2019-09-09 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190909_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 14, 11, 55, 699681)),
        ),
    ]
