# Generated by Django 2.2.4 on 2019-09-09 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190909_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 14, 14, 33, 262670)),
        ),
    ]
