# Generated by Django 2.2.4 on 2019-09-09 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190909_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 5, 16, 7, 61830, tzinfo=utc)),
        ),
    ]
