# Generated by Django 2.2.4 on 2019-09-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190909_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_subscribe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscribe_expire',
        ),
    ]
