# Generated by Django 2.2.4 on 2019-09-09 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190909_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 15, 38, 56, 318185)),
        ),
    ]
