# Generated by Django 2.2.4 on 2019-09-09 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190909_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribe_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 15, 40, 4, 614400)),
        ),
    ]
